[package]
name = "origami-engine"
version = "0.1.0-alpha.1"
edition = "2021"
description = "A templating engine for rust"
license = "MIT"
repository = "https://github.com/ratnaraj7/origami"
keywords = ["templates", "engine", "markup", "html", "web"]
categories = ["template-engine"]

[dependencies]
