on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: boa-dev/criterion-compare-action@v3
        with:
          # `benchName` is required. Omitting it will result in an error: `Unrecognized option: 'save-baseline'`.
          # Refer to the documentation for more details:
          # https://github.com/boa-dev/criterion-compare-action?tab=readme-ov-file#unrecognized-option-save-baseline
          benchName: "origami"
          features: "html_escape,minify_html,axum"
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
