name: tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --no-default-features --verbose
      - name: Run tests
        run: cargo test --no-default-features -F axum,html_escape,minify_html --verbose
